# Generated by Django 5.2.4 on 2025-07-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.CharField(primary_key=True, serialize=False)),
                ('trade_date', models.DateTimeField()),
                ('gross_pnl', models.FloatField()),
                ('fee', models.FloatField()),
                ('net_pnl', models.FloatField()),
            ],
        ),
    ]
