# Generated by Django 5.2.4 on 2025-07-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateTimeField()),
                ('gross_pnl', models.IntegerField()),
                ('fee', models.FloatField()),
                ('net_pnl', models.FloatField()),
                ('trade_id', models.CharField()),
            ],
        ),
    ]
