# Generated by Django 5.2.4 on 2025-07-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnl_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='gross_pnl',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trades',
            name='trade_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
